server:
  port: 8001

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
          - classpath:/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
